apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-volume 
  namespace: jenkins
  labels:
    type: local 
spec:
  storageClassName: local-prom-volume 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prom-volume
  namespace: jenkins
spec:
  storageClassName: local-prom-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi